# Generated by Django 5.0.14 on 2026-04-05 05:52

import django.core.validators
import django.db.models.deletion
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_expense_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('federal', 'Federal'), ('kotak', 'Kotak'), ('sbi', 'SBI'), ('hdfc', 'HDFC'), ('icici', 'ICICI')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('license', 'Driving Licence'), ('pan', 'PAN Card'), ('rc', 'Vehicle RC')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('document_number', models.CharField(blank=True, max_length=40)),
                ('notes', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to=tracker.models.document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
            },
        ),
    ]
