# Generated by Django 5.0.14 on 2026-04-05 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_replace_document_with_card_vault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('sunrise', 'Sunrise'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('berry', 'Berry'), ('graphite', 'Graphite'), ('gold', 'Gold')], default='ocean', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('note', models.CharField(blank=True, max_length=220)),
                ('remind_on', models.DateField()),
                ('remind_at', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_on', 'remind_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('sunrise', 'Sunrise'), ('ocean', 'Ocean'), ('forest', 'Forest'), ('berry', 'Berry'), ('graphite', 'Graphite'), ('gold', 'Gold')], default='ocean', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
